### PR TITLE
Make urlCache as a part of load context (#707)

### LINKED ISSUE #707: Run `openapiTS` two times in row throws an Error
Hey,

I've found an interesting issue with openapiTS: adding one more call of this function in tests/remote-schema/remote-schema.test.ts makes it fails. You may try to run this and you with get the following error:

```typescript
import path from "path";
import openapiTS from "../../src/index";

describe("remote $refs", () => {
  it("resolves remote $refs", async () => {
    // vvv Add this line vvv
    await openapiTS(path.join(__dirname, "spec", "spec.yml"));
    const types = await openapiTS(path.join(__dirname, "spec", "spec.yml"));
    expect(types).toEqual(`/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
… (content not changed)
```

The Error message: `🚏 version missing from schema; specify whether this is OpenAPI v3 or v2 https://swagger.io/specification`

### PR DESCRIPTION
**Pull request by mbelsky**
Closes #707

### CODE REVIEW

File: src/load.ts [hunk 1]
```diff
@@ -54,16 +54,16 @@ export function resolveSchema(url: string): URL {
...
 
-// temporary cache for load()
-let urlCache = new Set<string>(); // URL cache (prevent URLs from being loaded over and over)
-
 /** Load a schema from local path or remote URL */
 export default async function load(
   schema: URL | PartialSchema,
   options: LoadOptions
 ): Promise<{ [url: string]: PartialSchema }> {
+  const urlCache = options.urlCache || new Set<string>();
```
Comment (ericzorn93) [inline src/load.ts:65]: How can we ensure that the cache object being passed in is of type `Set` when the user is consuming the library with vanilla JS? They will have types provided, but it will not throw an error if they pass a different data structure.

Comment (mbelsky) [reply src/load.ts:65]: Thanks for asking. As I see this function is not a part of the library public api. And the function uses the cache object for recursive calls optimization. Also as you may see the function does not check types of the other fields of LoadOptions.

**Comment by mbelsky** [comment]
Hey @drwpow 

I've made two tests runs on my local machine: one on the main branch and one on the pr/pass-cache-in-context. And the tests run time difference is about 100ms. So I'm not sure how may I optimize the pr changes to make the tests pass. If you have any ideas about this issue I would like to hear about it.

<details>
<summary>Run tests on the main branch</summary>

```
~/gh/mb-openapi-ts (main)$ npm test -- ./tests/v3/index.test.ts 

> openapi-typescript@4.0.2 test
> npm run build && jest --no-cache "./tests/v3/index.test.ts"


> openapi-typescript@4.0.2 build
> rm -rf dist && tsc --project tsconfig.esm.json && tsc --project tsconfig.cjs.json

 PASS  tests/v3/index.test.ts (48.591 s)
  cli
    ✓ reads github.yaml spec (v3) from file (4074 ms)
    ✓ reads github.yaml spec (v3) from file (additional properties) (4303 ms)
    ✓ reads github.yaml spec (v3) from file (immutable types) (4329 ms)
    ✓ reads manifold.yaml spec (v3) from file (1075 ms)
    ✓ reads manifold.yaml spec (v3) from file (additional properties) (1076 ms)
    ✓ reads manifold.yaml spec (v3) from file (immutable types) (1064 ms)
    ✓ reads null-in-enum.yaml spec (v3) from file (694 ms)
    ✓ reads null-in-enum.yaml spec (v3) from file (additional properties) (698 ms)
    ✓ reads null-in-enum.yaml spec (v3) from file (immutable types) (695 ms)
    ✓ reads petstore-openapitools.yaml spec (v3) from file (830 ms)
    ✓ reads petstore-openapitools.yaml spec (v3) from file (additional properties) (829 ms)
    ✓ reads petstore-openapitools.yaml spec (v3) from file (immutable types) (824 ms)
    ✓ reads petstore.yaml spec (v3) from file (821 ms)
    ✓ reads petstore.yaml spec (v3) from file (additional properties) (830 ms)
    ✓ reads petstore.yaml spec (v3) from file (immutable types) (832 ms)
    ✓ reads stripe.yaml spec (v3) from file (3238 ms)
    ✓ reads stripe.yaml spec (v3) from file (additional properties) (3899 ms)
    ✓ reads stripe.yaml spec (v3) from file (immutable types) (3711 ms)
    ✓ reads spec (v3) from remote resource (1196 ms)
  json
    ✓ reads github.yaml from JSON (6150 ms)
    ✓ reads manifold.yaml from JSON (235 ms)
    ✓ reads null-in-enum.yaml from JSON (33 ms)
    ✓ reads petstore-openapitools.yaml from JSON (82 ms)
    ✓ reads petstore.yaml from JSON (87 ms)
    ✓ reads stripe.yaml from JSON (3399 ms)

Test Suites: 1 passed, 1 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        48.72 s
Ran all test suites matching /.\/tests\/v3\/index.test.ts/i.
```
</details>

<details>
<summary>Run tests on the pr/pass-cache-in-context branch</summary>

```
~/gh/mb-openapi-ts (pr/pass-cache-in-context)$ npm test -- ./tests/v3/index.test.ts 

> openapi-typescript@4.0.2 test
> npm run build && jest --no-cache "./tests/v3/index.test.ts"


> openapi-typescript@4.0.2 build
> rm -rf dist && tsc --project tsconfig.esm.json && tsc --project tsconfig.cjs.json

 PASS  tests/v3/index.test.ts (48.653 s)
  cli
    ✓ reads github.yaml spec (v3) from file (4115 ms)
    ✓ reads github.yaml spec (v3) from file (additional properties) (4447 ms)
    ✓ reads github.yaml spec (v3) from file (immutable types) (4273 ms)
    ✓ reads manifold.yaml spec (v3) from file (902 ms)
    ✓ reads manifold.yaml spec (v3) from file (additional properties) (946 ms)
    ✓ reads manifold.yaml spec (v3) from file (immutable types) (940 ms)
    ✓ reads null-in-enum.yaml spec (v3) from file (610 ms)
    ✓ reads null-in-enum.yaml spec (v3) from file (additional properties) (616 ms)
    ✓ reads null-in-enum.yaml spec (v3) from file (immutable types) (608 ms)
    ✓ reads petstore-openapitools.yaml spec (v3) from file (739 ms)
    ✓ reads petstore-openapitools.yaml spec (v3) from file (additional properties) (724 ms)
    ✓ reads petstore-openapitools.yaml spec (v3) from file (immutable types) (740 ms)
    ✓ reads petstore.yaml spec (v3) from file (754 ms)
    ✓ reads petstore.yaml spec (v3) from file (additional properties) (827 ms)
    ✓ reads petstore.yaml spec (v3) from file (immutable types) (841 ms)
    ✓ reads stripe.yaml spec (v3) from file (3809 ms)
    ✓ reads stripe.yaml spec (v3) from file (additional properties) (4025 ms)
    ✓ reads stripe.yaml spec (v3) from file (immutable types) (3712 ms)
    ✓ reads spec (v3) from remote resource (1226 ms)
  json
    ✓ reads github.yaml from JSON (6001 ms)
    ✓ reads manifold.yaml from JSON (224 ms)
    ✓ reads null-in-enum.yaml from JSON (27 ms)
    ✓ reads petstore-openapitools.yaml from JSON (75 ms)
    ✓ reads petstore.yaml from JSON (83 ms)
    ✓ reads stripe.yaml from JSON (3258 ms)

Test Suites: 1 passed, 1 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        48.798 s
Ran all test suites matching /.\/tests\/v3\/index.test.ts/i.
```
</details>

**Comment by kamsar** [comment]
The lack of this fix really crippled my attempt to use the node API, since the cache lives forever - and does not actually add the cached schema to the second and later call, i.e. 

```
if (urlCache.has(schemaID))
            return options.schemas;
```

In the above code in a second or later function invocation, urlCache will have the schema cached - but `options.schemas` will NOT contain it, resulting in spuriously unresolved externals in the output.

**Review by drwpow — APPROVED** [review]
Awesome fix! Thank you.

**Comment by drwpow** [comment]
@all-contributors please add @mbelsky for code, bug

**Comment by drwpow** [comment]
Released in `4.1.1`!

**Comment by kamsar** [comment]
@drwpow thanks so much, really appreciate this fix :)
