### PR TITLE
Fix js-yaml $ref

### LINKED ISSUE #1093: use the same openapi, json file generate ok, but yaml file generate error
**Description**

the same openapi:
when use openapi.yaml have a generate bug.
when use openapi.json no generate bug.

use openapi.yaml generate error data:
```
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/root/v4/getQueryParams1-v4": {
    get: {
      parameters: {
        query: {
          /** @description activityBases */
          activityBases: (external["components[%22schemas%22][%22ActivityBase%22]"])[];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": string;
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    getQueryParams1Request: {
      /** @description activityBases */
      activityBases: (external["components[%22schemas%22][%22ActivityBase%22]"])[];
    };
    ActivityBase: {
      name: string;
    } & {
      id: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.2.4`                      |
| Node.js              | `16.14.0`                      |
| OS + version         | `macOS 13, Windows 10, etc.` |

**Reproduction**

_How can this be reproduced / when did the error occur?_

openapi.json
```
{
  "openapi": "3.1.0",
  "info": {
    "title": "custom title",
    "license": {
      "name": "This file is auto generated, do not edit!"
    },
    "version": "0.4.1"
  },
  "paths": {
    "/root/v4/getQueryParams1-v4": {
      "get": {
        "tags": ["Test4"],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "activityBases",
            "in": "query",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/ActivityBase"
              }
            },
            "description": "activityBases"
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "getQueryParams1Request": {
        "type": "object",
        "properties": {
          "activityBases": {
            "description": "activityBases",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ActivityBase"
            }
          }
        },
        "required": ["activityBases"]
      },
      "ActivityBase": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              }
            },
            "required": ["name"]
          },
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "number"
              }
            },
            "required": ["id"]
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Test4",
      "description": "Test3Controller 注释\n注释3"
    }
  ]
}
```

openapi.yaml
```
openapi: 3.1.0
info:
  title: custom title
  license:
    name: This file is auto generated, do not edit!
  version: 0.4.1
paths:
  /root/v4/getQueryParams1-v4:
    get:
      tags:
        - Test4
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
      parameters:
        - name: activityBases
          in: query
          required: true
          schema:
            type: array
            items: &ref_0
              $ref: '#/components/schemas/ActivityBase'
          description: activityBases
components:
  schemas:
    getQueryParams1Request:
      type: object
      properties:
        activityBases:
          description: activityBases
          type: array
          items: *ref_0
      required:
        - activityBases
    ActivityBase:
      allOf:
        - type: object
          properties:
            name:
              type: string
          required:
            - name
        - type: object
          properties:
            id:
              type: number
          required:
            - id
tags:
  - name: Test4
    description: |-
      Test3Controller 注释
      注释3
```

**Expected result**

```
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/root/v4/getQueryParams1-v4": {
    get: {
      parameters: {
        query: {
          /** @description activityBases */
          activityBases: (components["schemas"]["ActivityBase"])[];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": string;
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    getQueryParams1Request: {
      /** @description activityBases */
      activityBases: (components["schemas"]["ActivityBase"])[];
    };
    ActivityBase: {
      name: string;
    } & {
      id: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
```

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1093. Supercedes #1097.

## How to Review

Tests should pass

## Checklist

- [x] Unit tests updated
- [x] README updated
- [x] `examples/` directory updated (only applicable for openapi-typescript)

### CODE REVIEW

File: packages/openapi-typescript/src/utils.ts [hunk 1]
```diff
@@ -106,15 +106,31 @@ export function comment(text: string, indentLv?: number): string {
...
-  return {
-    filename: filename || ".",
-    path: path
-      .split("/") // split by special character
-      .filter((p) => !!p && p !== "properties") // remove empty parts and "properties" (gets flattened by TS)
-      .map(decodeRef), // decode encoded chars
-  };
+
+  // OpenAPI $ref
+  if (ref.includes("#/")) {
```
Comment (drwpow) [inline packages/openapi-typescript/src/utils.ts:111]: Was able to get a 2x speedup of `parseRef` out of refactoring it a little. Which is something, because this is used quite a lot.
