### PR TITLE
Fix remote schema maps

### LINKED ISSUE #1131: Generation of schema that references outside schema
**Description**

Generation of a schema, that references other schemas in the $ref results in a invalid schema.ts, with "unkown" types and wrong property referencing `Property 'Problem' does not exist on type 'unknown'`

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.2.4`                      |
| Node.js              | `20.1.0`                      |
| OS + version         | `macOS 13, Windows 11, etc.` |

**Reproduction**

Run following code as a .yml in the generator:
```yml
openapi: 3.0.0
servers:
  - url: https://dummy.to.server/v1
info:
  description: Test YAML
  version: 0.1.0
  title: Test
  termsOfService: ''
security:
  - bearerAuth: [ ]
tags:
  - name: Test Object
    description: Basic operations on a test object
paths:
  /test-object/{uuid}:
    get:
      summary: Returns a test object
      tags:
        - Test Object
      description: Returns a single test object if exists
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      operationId: getLatestTOByUUID
      responses:
        '200':
          description: Test Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestObject'
        '404':
          description: Test Object not found
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.0.yaml#/Problem'
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.0.yaml#/Problem'
components:
  schemas:
    TestObject:
      type: object
      properties:
        uuid:
          type: string
        id:
          type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

_How can this be reproduced / when did the error occur?_

Generate a schema based on the prior .yml file.

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1131. There are likely some other bugs with deeply-nested remote schemas, but this fixes at least one.

The reason was in our `getHint()` logic that traverses the nodePath, it wasn’t keeping track of remote filenames, which is necessary for certain inferences (the hints are necessary because partial schemas could be _anything_ and still be valid—the only way to know is by tracing from the root). There’s probably a better solution than this, but this will do for now.

## How to Review

Tests should pass.

## Checklist

- [x] Unit tests updated
- [ ] README updated
- [x] `examples/` directory updated (only applicable for openapi-typescript)

### CODE REVIEW

File: packages/openapi-typescript/examples/digital-ocean-api.ts [hunk 1]
```diff
@@ -3965,7 +3965,160 @@ export interface external {
       default: external["shared/responses/unexpected_error.yml"];
     };
   }
-  "resources/certificates/models/certificate_create.yml": unknown
```
Comment (drwpow) [inline packages/openapi-typescript/examples/digital-ocean-api.ts:3968]: 🤔 this is probably a good sign

File: packages/openapi-typescript/src/load.ts [hunk 2]
```diff
@@ -306,105 +309,116 @@ function relativePath(src: URL, dest: URL): string {
...
+function getHintFromSchemaObject(path: (string | number)[], external: boolean): Subschema["hint"] {
   switch (path[0]) {
     case "allOf":
     case "anyOf":
     case "oneOf":
-      return getHintFromSchemaObject(path.slice(2)); // skip array index at [1]
+      return getHintFromSchemaObject(path.slice(2), external); // skip array index at [1]
+  }
+  // if this is external, and the path is [filename, key], then the external schema is probably a SchemaMap
+  if (path.length === 2 && external) {
```
Comment (drwpow) [inline packages/openapi-typescript/src/load.ts:419]: Very wacky logic, but it seems to check out 🤷
