### PR TITLE
Fix extra quote generated in components/responses with $refs

### LINKED ISSUE #1323: Missing double quote in the "responses" section
**Description**

The Typescript generated code is broken, a double quote (`"`) is missing in the "responses" section.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.5.3`                      |
| Node.js              | `18.15.0`                      |

**Reproduction**

Swagger:
```yaml
openapi: 3.0.3
info:
  title: Sample
  version: 0.0.1
paths:
  /ping:
    get:
      responses:
        400:
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: "string"
  responses:
    ErrorResponse:
      $ref: '#/components/schemas/GeneralError'
```

Generated code:
```
export interface paths {
  "/ping": {
    get: {
      responses: {
        400: components["responses"]["ErrorResponse"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    GeneralError: {
      code?: string;
    };
  };
  responses: {
    ErrorResponse": components["schemas"]["GeneralError"]; // <-- the line should start with double quote
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;
export type external = Record<string, never>;
export type operations = Record<string, never>;
```

**Expected result**

Expected code:
```
  responses: {
    "ErrorResponse": components["schemas"]["GeneralError"]; // <-- the line should start with double quote
  };
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1323. Adds test to prevent future regression.

This was just a small but devastating typo that went unnoticed for a while 😓 

## How to Review

- Tests should pass

## Checklist

- [x] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [x] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

File: packages/openapi-typescript/test/helpers.ts [hunk 1]
```diff
@@ -1,12 +0,0 @@
-import fs from "node:fs";
-
-export const CLRF_RE = /\r\n/g;
-
-/** Normalize all linebreaks to \n when reading files (for Windows tests) */
-export function readFile(filepath: fs.PathOrFileDescriptor): string {
```
Comment (drwpow) [inline packages/openapi-typescript/test/helpers.ts:6]: Turns out this is built in to Vitest. So now we just use `.toMatchFileSnapshot()` instead

Sidenote for readers: I don’t like “traditional” snapshots for 2 reasons:
1. I believe snapshots shouldn’t have any test runner artifacts/comments and should be 100% human-readable (otherwise, you miss changes)
2. I don’t like making snapshots easy to update in a project like this—the snapshots are everything. I want failures to be meaningful, and require investigation into the _why_ something changed, and to not disappear with the simple addition of a `-u` flag.
