### PR TITLE
Fix remote $refs to complete schemas

### LINKED ISSUE #1041: External Refs don't work in v6
**Description**

If you have an Open API Specification in YAML which references another Open API Specification, say in order to support common types, the code is not correctly generated in v6 compared to the code generated in v5.

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `5.4.1` and `6.1.1`                      |
| Node.js              | `18.14.2`                      |
| OS + version         | `macOS 13.2.1` |

**Reproduction**

Given a Common.yaml containing:

```yaml
openapi: 3.1.0
info:
  title: Common API Components
  version: 1.0.0
  summary: The common API Components
components:
  schemas:
    User:
      title: User
      type: object
      description: Example User
      examples:
        - id: 142
          firstName: Alice
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
      required:
        - id
        - firstName
```

Given an api.yaml which references common.yaml:

```yaml
openapi: 3.1.0
x-stoplight:
  id: 42f45qvowo3cx
info:
  title: Sample API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: common.yaml#/components/schemas/User
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
components:
  schemas: {}
```

When the command (v5) is run: `npx --yes openapi-typescript@5 ./api.yaml --output out.v5.ts` the following is output to screen:

```bash
✨ openapi-typescript 5.4.1
🚀 ./api.yaml -> /Users/xxxx/Documents/StoplightStudio/codegen-sample/reference/out.v5.ts [102ms]
```

The generated `out.v5.ts` contains, the following external block:

```typescript
export interface external {
  "common.yaml": {
    paths: {};
    components: {
      schemas: {
        /**
         * User
         * @description Example User
         */
        User: {
          /** @description Unique identifier for the given user. */
          id: number;
          firstName: string;
        };
      };
    };
    operations: {};
  };
}
```

When the command (v6) is run: `npx --yes openapi-typescript@6 ./api.yaml --output out.v6.ts` the following is output to screen:

```bash
✨ openapi-typescript 6.1.1
🚀 ./api.yaml → file:///Users/xxxx/Documents/StoplightStudio/codegen-sample/reference/out.v6.ts [28ms]
```

The generated `out.v6.ts` contains, the following external block:

```typescript
export interface external {

  "common.yaml": Record<string, never>
}
```

**Expected result**

Version 6 external code should be generated as per version 5 external code.

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1041. The test suite only included examples of partial schemas for remote $refs, so complete schemas were broken. This supports complete remote schemas; there was just a bug in parsing. This fixes that issue and adds a test.

## How to Review

Tests cover the changes; tests should pass.

## Checklist

- [x] Unit tests updated
- [x] README updated
- [x] `examples/` directory updated (if applicable)

### CODE REVIEW

File: examples/digital-ocean-api.ts [hunk 1]
```diff
@@ -684,11 +684,10 @@ export interface components {
 
 export interface external {
   "description.yml": {
-
     paths: Record<string, never>;
     webhooks: Record<string, never>;
     components: Record<string, never>;
-  }
```
Comment (drwpow) [inline examples/digital-ocean-api.ts:691]: Also fixes an insignificant but nevertheless present TS formatting bug

File: src/load.ts [hunk 2]
```diff
@@ -238,8 +238,9 @@ export default async function load(
       return;
     }
 
-    // hints help external schemas pick up where the root left off
-    const hint = getHint([...nodePath, ...ref.path], options.hint);
+    // hints help external partial schemas pick up where the root left off (for external complete/valid schemas, skip this)
+    const isRemoteFullSchema = ref.path[0] === "paths" || ref.path[0] === "components"; // if the initial ref is "paths" or "components" this must be a full schema
+    const hint = isRemoteFullSchema ? "OpenAPI3" : getHint([...nodePath, ...ref.path], options.hint);
```
Comment (drwpow) [inline src/load.ts:243]: This was the erring code—given a path, we try and create a “hint” for any given subschema.

The reason hints are necessary is because the top-level keys of a schema can be anything, and there are no reserved words. For example, if `parameters` is a top-level property, is this subschema referring to properties on a SchemaObject? Or is this `#/components/parameters`? Or is this part of an operation object? We can only know by tracing the path from the root schema.

Of course, this whole process can be skipped for complete, valid schemas—and that’s exactly what this fix does.

File: src/utils.ts [hunk 3]
```diff
@@ -256,7 +256,11 @@ export function escObjKey(input: string): string {
 
 /** Indent a string */
 export function indent(input: string, level: number) {
-  return "  ".repeat(level).concat(input);
+  if (level > 0) {
+    return "  ".repeat(level).concat(input);
+  } else {
+    return input;
```
Comment (drwpow) [inline src/utils.ts:262]: Minor change to `indent()`—this isn’t needed for valid schemas, but for invalid schemas this often is the thing to throw an error and it seems broken.

File: src/index.ts [hunk 4]
```diff
@@ -131,16 +131,16 @@ async function openapiTS(
       let comment: string | undefined;
       switch (subschema.hint) {
         case "OpenAPI3": {
-          const subschemaTypes = transformSchema(subschema.schema, { ...ctx, indentLv });
+          const subschemaTypes = transformSchema(subschema.schema, { ...ctx, indentLv: indentLv + 1 });
           if (!Object.keys(subschemaTypes).length) break;
-          output.push(indent(`${key}: {`, 1), "");
+          output.push(indent(`${key}: {`, indentLv));
```
Comment (drwpow) [inline src/index.ts:136]: Minor formatting changes here that don’t affect generation; these were just preexisting bugs that weren’t caught from the original lack of testing.
