### PR TITLE
Change additionalProperties default

### LINKED ISSUE #607: New additionalProperties default breaks `oneOf`
I experience exactly the problem that @radist2s described in https://github.com/drwpow/openapi-typescript/pull/585#issuecomment-840149431:

```json
{
  "pictures": {
    "type": "array",
    "items": {
      "oneOf": [
        {
          "type": "integer"
        },
        {
          "$ref": "#/components/schemas/ItemsArtworksPictures"
        }
      ]
    }
  }
}
```
results in 
```typescript
{
  pictures?: ((number | components["schemas"]["ItemsArtworksPictures"]) & {
    [key: string]: any;
  })[];
}
```
which is useless (and wrong I hope?).

I'm reverting to `3.2.3` for now but it'd be great to have this fixed soon! :)

### PR DESCRIPTION
**Pull request by drwpow**
Resolves #607. A recent change (#585) allowed for the automatic addition of additional properties, so `& { [key: string]: any }` was added to all schema objects. The intent was to better reflect OpenAPI’s specification, and there is precedent for that. However, based on feedback, and previous expectations this library set, it was a little too disruptive.

And so, this PR reverts that behavior, turning this **off by default**`, but adding a new `--additional-properties` flag to enable this behavior (outlined in the README). This is a good compromise of allowing that behavior, but requiring it to be opt-in (which is also probably better to be stricter by default).

### CODE REVIEW

File: src/transform/index.ts [hunk 1]
```diff
@@ -1,165 +1,137 @@
...
+    const required = new Set(Object.keys(schema));
+    switch (ctx.version) {
       case 2: {
-        return `export interface definitions {\n  ${transformSchemaObjMap(schema, {
-          formatter,
-          immutableTypes,
-          required: Object.keys(schema),
-          version,
-        })}\n}`;
+        output.definitions = transformSchemaObjMap(schema, { ...ctx, required });
```
Comment (drwpow) [inline src/transform/index.ts:22]: Changing `transformAll()`’s default output to be an object rather than a string is required for the upcoming #602. But I wanted to get that change in before we release v4, so that v3 patches will be easier to work on (less codebase distance between v3 and v4)
