### PR TITLE
Fix bugs with remote $refs, add cwd option for JSON schema parsing

### LINKED ISSUE #938: Not generating types for remote $ref in path parameters
#### Description
When attempting to generate code from an OpenAPI document that included remote $ref as path parameters (storeNumber), these path parameters are ignored when types are generated.

#### openapi-generator version
5.4.1

#### node version
14.17.6

#### OpenAPI declaration file content

```yaml
openapi: 3.1.0
x-stoplight:
  id: f8f10zekkrr1n
info:
  title: Test
  version: '1.0'
  summary: API to manage customers database
  description: This api will be used to manage data in the customers database
  contact:
    name: Company Name
servers:
  - url: 'http://localhost:3000'
paths:
  '/customers/{storeNumber}/{customerId}':
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
        description: customer unique identifier
      - $ref: ./common.yaml#/components/parameters/storeNumber
    get:
      summary: Get User Info by User ID
      tags:
        - Customers
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
      description: Update the information of an existing user.
      tags:
        - Customers
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
tags:
  - name: Customers
```
 
#### Code generated

```typescript
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export interface paths {
  '/customers/{storeNumber}/{customerId}': {
    /** Retrieve the information of the user with the matching user ID. */
    get: operations['get-users-userId'];
    /** Update the information of an existing user. */
    patch: operations['patch-users-userId'];
    parameters: {
      path: {
        /** customer unique identifier */
        customerId: string;
      };
    };
  };
}
export interface components {
  schemas: {
    /** User */
    User: {
      /** @description Unique identifier for the given user. */
      id: number;
      firstName: string;
      lastName: string;
      /** Format: email */
      email: string;
      /**
       * Format: date
       * @example 1997-10-31
       */
      dateOfBirth?: string;
      /** @description Set to true if the user's email has been verified. */
      emailVerified: boolean;
      /**
       * Format: date
       * @description The date that the user was created.
       */
      createDate?: string;
    };
  };
}
export interface operations {
  /** Retrieve the information of the user with the matching user ID. */
  'get-users-userId': {
    parameters: {
      path: {
        /** customer unique identifier */
        customerId: string;
      };
    };
    responses: {
      /** User Found */
      200: {
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  /** Update the information of an existing user. */
  'patch-users-userId': {
    parameters: {
      path: {
        /** customer unique identifier */
        customerId: string;
      };
    };
    responses: {
      /** User Updated */
      200: {
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
    /** Patch user properties to update. */
  };
}
export interface external {
  'common.yaml': {
    paths: {};
    components: {
      schemas: {};
      parameters: {
        /** @description The store number, in four digit format (leading zero padded) */
        storeNumber: string;
      };
    };
    operations: {};
  };
}
```
#### Issue:
I cannot reference the type `paths['/customers/{storeNumber}/{customerId}]['parameters']['path']['storeNumber']` because it has not been generated.

##### Expected: 
```typescript
export interface paths {
  '/customers/{storeNumber}/{customerId}': {
    /** Retrieve the information of the user with the matching user ID. */
    get: operations['get-users-userId'];
    /** Update the information of an existing user. */
    patch: operations['patch-users-userId'];
    parameters: {
      path: {
        /** customer unique identifier */
        customerId: string;
       /** The store number, in four digit format (leading zero padded) */
        storeNumber: string;
      };
    };
  };
}
```
##### Actual:
```typescript
export interface paths {
  '/customers/{storeNumber}/{customerId}': {
    /** Retrieve the information of the user with the matching user ID. */
    get: operations['get-users-userId'];
    /** Update the information of an existing user. */
    patch: operations['patch-users-userId'];
    parameters: {
      path: {
        /** customer unique identifier */
        customerId: string;
      };
    };
  };
}
```

#### Similar issue:

#918

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #938, Partially addresses #1307 by fixing remote `$ref` generation and adding the ability to specify `cwd` for dynamic JSON root schemas

## How to Review

- Tests added; tests should pass

## Checklist

- [x] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [ ] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

File: packages/openapi-typescript/examples/digital-ocean-api.ts [hunk 1]
```diff
@@ -705,7 +705,7 @@ export interface external {
      * @example 50a994b6-c303-438f-9495-7e896cfe6b08
      */
     cluster_uuid: string;
-  }
+  };
```
Comment (drwpow) [inline packages/openapi-typescript/examples/digital-ocean-api.ts:708]: Minor fix of missing semi
