### PR TITLE
504 - Fix additionalProperties on object type

### LINKED ISSUE #504: Schema handles object with additionalProperties: "true" or "{}" wrongly
As per definition https://swagger.io/docs/specification/data-models/dictionaries/  setting additionalProperties to "true" or "{}"
allows the value to be of any type. 

Example: The swagger.json contains something along:

```
"foo": {
    "type": "object",
    "additionalProperties": { },
},
```

openapi-typescript would generate:

```
foo?: { [key: string]: { [key: string]: any } }
```

Expected:
```
foo?: { [key: string]: any }
```

This issue is related to https://github.com/drwpow/openapi-typescript/issues/311.

### PR DESCRIPTION
**Pull request by FabioWanner**
Fixes #504 
As stated in the [documentation ](https://swagger.io/docs/specification/data-models/dictionaries/) Freeform objects (objects with any value) can be defined by setting additionalProperties either to true or {}. 

Previously:
```
foo?: { [key: string]: { [key: string]: any } }
```
was the output instead of:
```
foo?: { [key: string]: any }
```

This is fixed and tested with this PR.

### CODE REVIEW

File: src/transform/schema.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export function transformSchemaObj(node: any): string {
       // if additional properties, add an intersection with a generic map type
       let additionalProperties: string | undefined;
       if (node.additionalProperties) {
-        if (node.additionalProperties === true) {
+        if (node.additionalProperties === true || Object.keys(node.additionalProperties).length === 0) {
```
Comment (drwpow) [inline src/transform/schema.ts:97]: 👍🏻

File: tests/schema.test.ts [hunk 2]
```diff
@@ -163,6 +163,9 @@ describe("SchemaObject", () => {
       // boolean
       expect(transform({ additionalProperties: true })).toBe(`{ [key: string]: any }`);
 
+      // empty object
+      expect(transform({ additionalProperties: {} })).toBe(`{ [key: string]: any }`);
```
Comment (drwpow) [inline tests/schema.test.ts:167]: Great test!

**Review by drwpow — APPROVED** [review]

**Comment by drwpow** [comment]
@all-contributors please add @FabioWanner for bug, code, test
