### PR TITLE
Fix missing parameters in operation object

### LINKED ISSUE #1065: `parameters` defined directly under a path no longer gets merged to parameters defined under a specific operation for that path
**Description**

When `parameters` are defined for all operations under a path (common usage is for path params), as of v6 they are no longer added to the parameters of every operation under it.

In the examples below, notice how `thread_id` use to be added to the definition of `get_comment_resource` and `post_comment_resource`. Under v6, that is no longer the case.

**OpenAPI**

```json
{
  "openapi": "3.0.2",
  "servers": [],
  "paths": {
    "/v1/auth/comments/{thread_id}": {
      "get": {
        "operationId": "get_comment_resource",
        "parameters": [
          {
            "in": "query",
            "name": "page_size",
            "required": false,
            "schema": {
              "default": 20,
              "maximum": 100,
              "minimum": 1,
              "type": "integer"
            }
          },
          {
            "in": "query",
            "name": "start",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "type": "string"
          }
        }
      },
      "parameters": [
        {
          "in": "path",
          "name": "thread_id",
          "required": true,
          "type": "string"
        }
      ],
      "post": {
        "operationId": "post_comment_resource",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "body": {
                    "type": "string"
                  },
                  "parent_id": {
                    "type": "string"
                  }
                },
                "required": ["body"],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "type": "string"
          }
        }
      }
    }
  },
  "components": {
    "schemas": []
  }
}
```

**Generated TS**

```ts
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/auth/comments/{thread_id}': {
    get: operations['get_comment_resource']
    post: operations['post_comment_resource']
    parameters: {
      path: {
        thread_id: string
      }
    }
  }
}

export type webhooks = Record<string, never>
export type external = Record<string, never>

export interface operations {
  get_comment_resource: {
    parameters: {
      query: {
        page_size?: number
        start?: string
      }
    }
    responses: {
      200: never
    }
  }
  post_comment_resource: {
    requestBody: {
      content: {
        'application/json': {
          body: string
          parent_id?: string
        }
      }
    }
    responses: {
      201: never
    }
  }
}

```

**Expected TS, output from v5.4.1*

```ts
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/auth/comments/{thread_id}': {
    get: operations['get_comment_resource']
    post: operations['post_comment_resource']
    parameters: {
      path: {
        thread_id: unknown
      }
    }
  }
}

export interface operations {
  get_comment_resource: {
    parameters: {
      path: {
        thread_id: unknown
      }
      query: {
        page_size?: number
        start?: unknown
      }
    }
    responses: {
      200: unknown
    }
  }
  post_comment_resource: {
    parameters: {
      path: {
        thread_id: unknown
      }
    }
    responses: {
      201: unknown
    }
    requestBody: {
      content: {
        'application/json': {
          body: string
          parent_id?: string
        }
      }
    }
  }
}

export interface external {}
```

**Checklist**

- [ ] My OpenAPI schema passes a validator
- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1065. This was a dumb bug where we just didn’t do a complete parameter lookup if it had an `operationId` 🤦. Was as easy as moving a couple lines of code above the `if()` statement.

## How to Review

Captured in tests; tests should pass.

## Checklist

- [x] Unit tests updated
- [x] README updated
- [x] `examples/` directory updated (if applicable)

### CODE REVIEW

File: src/transform/path-item-object.ts [hunk 1]
```diff
@@ -24,25 +24,32 @@ export default function transformPathItemObject(
...
+        { path, ctx: { ...ctx, indentLv: 1 } }
+      );
       ctx.operations[operationObject.operationId] = {
         operationType,
         comment: getSchemaObjectComment(operationObject, 1),
       };
       output.push(indent(`${method}: operations[${escStr(operationObject.operationId)}];`, indentLv));
     } else {
-      // fold top-level PathItem parameters into method-level, with the latter overriding the former
-      const keyedParameters: Record<string, ParameterObject | ReferenceObject> = {};
```
Comment (drwpow) [inline src/transform/path-item-object.ts:40]: Just moves this up one level; that’s it!

File: src/types.ts [hunk 2]
```diff
@@ -276,7 +276,7 @@ export interface RequestBodyObject extends Extensable {
  */
 export interface MediaTypeObject extends Extensable {
   /** The schema defining the content of the request, response, or parameter. */
-  schema?: SchemaObject;
+  schema?: SchemaObject | ReferenceObject;
```
Comment (drwpow) [inline src/types.ts:279]: Irrelevant type bug that came up while writing the test

File: CONTRIBUTING.md [hunk 3]
```diff
@@ -40,15 +40,17 @@ This will compile the code as you change automatically.
...
 
 1. First, write a [test](#testing) that fully outlines what you’d _like_ the output to be.
-2. Make sure this test **fails** when you run `npm test` (yes, _fails!_)
+2. Next, make sure this test **fails** when you run `npm test` (yes, _fails!_)
 3. Then, make changes to `src/` until the tests pass.
 
-_Code generation is hard!_ And for that reason, starting with a very clear expectation of your end-goal can make working easier.
+Reasoning about code generation can be quite difficult until you “invert your thinking” and approach it output-first. Adopting TDD can turn very unclear/abstract problems into concrete ones with clear steps to resolution.
+
+✨ When starting any task, **write a failing test first!** ✨
```
Comment (drwpow) [inline CONTRIBUTING.md:53]: Tweaked wording of this to harp on how helpful TDD is when contributing.

I am not that smart. I need TDD to be able to do anything in this library :P
